noter/noter/urls.py
from django.urls import path

from . import views

app_name = 'noter'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('notebook/<int:notebook_id>/', views.notebook_view, name = 'notebook'),
    path('note/<int:note_id>/', views.note_view, name = 'note'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('register/', views.register_view, name = 'register'),
    path('create_notebook/', views.notebook_creation, name = 'notebook_create'),
    path('create_note/<int:notebook_id>/', views.note_creation, name = 'note_create'),
    path('note_delete/<int:note_id>/', views.note_delete, name = 'note_delete'),
    path('notebook_delete/<int:notebook_id>', views.notebook_delete, name = 'notebook_delete'),
    path('notebook_edit/<int:notebook_id>', views.notebook_edit, name = 'notebook_edit'),
    path('user_settings/', views.user_settings, name = 'user_settings'),
    path('access_denied/', views.access_denied, name = 'access_denied')
]

noter/yaripey_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('noter/', include('noter.urls')),
    path('admin/', admin.site.urls),
]

noter/noter/models.py
from django.db import models
from django.contrib.auth.models import User


class Notebook(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length = 30)
    desc = models.CharField(default = None, max_length = 300, null = True)
    def __str__(self):
        return self.name



class Note(models.Model):
    notebook = models.ForeignKey(Notebook, on_delete = models.CASCADE)
    title = models.CharField(default = None, max_length = 200, null = True)
    text = models.TextField()

    def __str__(self):
        return 'Note from ' + self.notebook.name

noter/noter/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Username", max_length=30)
    password = forms.CharField(label = "Password", widget = forms.PasswordInput)


class RegisterForm(forms.Form):
    firstname = forms.CharField(label = "First Name", max_length=50)
    lastname = forms.CharField(label = "Last Name", max_length=50)
    username = forms.CharField(label = "Username", max_length=30)
    email = forms.CharField(label = "Email", max_length=50, widget = forms.EmailInput)
    password1 = forms.CharField(label = "Password", max_length=50, widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Confirm Password", max_length=50, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 != password2:
            raise forms.ValidationError("Passwords doesn't match.")


class NotebookEditForm(forms.Form):
    name = forms.CharField(label = "Notebook name", max_length=30)
    desc = forms.CharField(label = "Notebook description", max_length=300)


class NoteEditForm(forms.Form):
    title = forms.CharField(label = "Note title", max_length=200, required=False)
    text = forms.CharField(label = "Note text", widget=forms.Textarea, required = False)


class EditUserForm(forms.Form):
    firstname = forms.CharField(label = "First Name", max_length=50)
    lastname = forms.CharField(label = "Last Name", max_length=50)
    username = forms.CharField(label = "Username", max_length=30)
    email = forms.CharField(label = "Email", max_length=50, widget = forms.EmailInput)

noter/noter/views.py
from django.shortcuts import render, redirect
from django.views import generic

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User

from django.db import IntegrityError

from django.urls import reverse

from .forms import LoginForm, RegisterForm, NotebookEditForm, NoteEditForm, EditUserForm

from .models import Notebook, Note

from .functions import smart_truncate

# Login page with all notebooks
@login_required
def index(request):
    user = request.user
    notebooks = Notebook.objects.all().filter(user = request.user)
    context = {'user': user, 'notebooks_list': notebooks}

    return render(request, 'noter/index.html', context)


# Login page
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            print(username + ' ' + password)
            user = authenticate(request, username = username, password = password)
            if user is not None:
                login(request, user)
                return redirect(reverse("noter:index"))
            else:
                context = {'form': form, 'error': 'Username or password are incorrect'}
                return render(request, 'noter/login.html', context)

    else:
        form = LoginForm()

    return render(request, 'noter/login.html', {'form': form})


# Logout view
@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("noter:login"))


# Registration page
def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.create_user(
                    form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password1']
                )
                user.first_name = form.cleaned_data['firstname']
                user.last_name = form.cleaned_data['lastname']
                user.save()
            except IntegrityError:
                context = {'form': form, 'error': 'User with such username already exists.'}
                return render(request, 'noter/register.html', context)
    else:
        form = RegisterForm()

    return render(request, 'noter/register.html', {'form': form})



# Notebook page with notes in it
@login_required
def notebook_view(request, notebook_id):
    user = request.user
    notebook = Notebook.objects.filter(id = notebook_id)[0]
    if notebook.user != user:
        return redirect(reverse("noter:access_denied"))
    notes = Note.objects.filter(notebook = notebook)
    for note in notes:
        note.text = smart_truncate(note.text, 150)
    context = {
        'user': user,
        'notebook': notebook,
        'notes': notes
    }
    return render(request, 'noter/notebook.html', context)


# Notebook creation page
@login_required
def notebook_creation(request):
    user = request.user
    form = NotebookEditForm(request.POST)
    context = {
        'user': user,
        'form': form
    }
    if form.is_valid():
        notebook_name = form.cleaned_data['name']
        notebook_desc = form.cleaned_data['desc']
        notebook = Notebook(
            user = user,
            name = notebook_name,
            desc = notebook_desc
        )
        notebook.save()
        return redirect(reverse("noter:index"))

    return render(request, 'noter/notebook_creation.html', context)


# Notebook edit page
@login_required
def notebook_edit(request, notebook_id):
    user = request.user
    notebook = Notebook.objects.filter(id = notebook_id)[0]
    if notebook.user != user:
        return redirect(reverse("noter:access_denied"))
    form = NotebookEditForm(initial = {
        'name': notebook.name,
        'desc': notebook.desc
    })
    if request.method == "POST":
        form = NotebookEditForm(request.POST)
        if form.is_valid():
            notebook.name = form.cleaned_data['name']
            notebook.desc = form.cleaned_data['desc']
            notebook.save()
            return redirect(reverse("noter:notebook", kwargs={'notebook_id': notebook.id}))
    context = {
        "user": user,
        "notebook": notebook,
        "form": form
    }

    return render(request, 'noter/edit_notebook.html', context)


# Notebook delete view
@login_required
def notebook_delete(request, notebook_id):
    user = request.user
    notebook = Notebook.objects.filter(id = notebook_id)[0]
    if notebook.user != user:
        return redirect(reverse("noter:access_denied"))
    notes = Note.objects.filter(notebook = notebook)
    for note in notes:
        note.delete()

    notebook.delete()
    return redirect(reverse("noter:index"))


# Note page
@login_required
def note_view(request, note_id):
    user = request.user
    note = Note.objects.filter(id = note_id)[0]
    if note.notebook.user != user:
        return redirect(reverse("noter:access_denied"))
    form = NoteEditForm(initial = {
        'title': note.title,
        'text': note.text
    })
    if request.method == 'POST':
        form = NoteEditForm(request.POST)
        if form.is_valid():
            note.title = form.cleaned_data['title']
            note.text = form.cleaned_data['text']
            note.save()
            return redirect(reverse("noter:notebook", kwargs={'notebook_id': note.notebook.id}))
    context = {
        'user': user,
        'note': note,
        'form': form,
        'notebook': note.notebook
    }

    return render(request, 'noter/note.html', context)



# Note creation view
@login_required
def note_creation(request, notebook_id):
    user = request.user
    notebook = Notebook.objects.filter(id = notebook_id)[0]
    if notebook.user != user:
        return redirect(reverse("noter:access_denied"))
    note = Note(
        notebook = notebook
    )
    note.save()
    return redirect(reverse("noter:note", kwargs={'note_id': note.id}))

# Note delete view
@login_required
def note_delete(request, note_id):
    note = Note.objects.filter(id = note_id)[0]
    notebook = note.notebook
    note.delete()
    return redirect(reverse("noter:notebook", kwargs = {'notebook_id': notebook.id}))


# User settings view
@login_required
def user_settings(request):
    user = request.user
    form = EditUserForm(initial = {
        'username': user.username,
        'email': user.email,
        'lastname': user.last_name,
        'firstname': user.first_name
    })
    if request.method == "POST":
        form = EditUserForm(request.POST)
        if form.is_valid():
            try:
                user.username = form.cleaned_data['username']
                user.email = form.cleaned_data['email']
                user.last_name = form.cleaned_data['lastname']
                user.first_name = form.cleaned_data['firstname']
                user.save()
            except IntegrityError:
                context = {
                    'user': user,
                    'form': form,
                    'error': 'User with such username already exists.'
                    }
                return render(request, 'noter/user_settings.html', context)
            return redirect(reverse("noter:user_settings"))
    context = {
        'user': user,
        'form': form
    }
    return render(request, 'noter/user_settings.html', context)


# Access denied view
def access_denied(request):
    return render(request, 'noter/access_denied.html')

noter/noter/templates/noter/access_denied.html
{% extends 'noter\base.html' %}

{% block content %}

    <div class="notes-content">
        <h2>Access denied.</h2>
        <h4>Please check your url adress again, or return to the main page.</h4>
        <a href="{% url 'noter:index' %}" class = 'button'>Main page1</a>
    </div>

{% endblock %}

noter/noter/templates/noter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My notes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'noter/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <div class="header">
        <a href="{% url 'noter:index' %}" class = "logo">Noter</a>
        {% if user %}
            <div class="header-right">
                Logged as: {{ user.first_name }} {{ user.last_name }} | <a href="{% url 'noter:user_settings' %}" class="settings">Settings</a> | <a href="{% url 'noter:logout' %}" class="logout">Logout</a>
            </div>
        {% endif %}
        <div style="clear: both;"></div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

noter/noter/templates/noter/edit_notebook.html
{% extends "noter\base.html" %}

{% block content %}

    <div class="notes-content">
        <h2>Edit your notebook:</h2>
        <form action="/noter/notebook_edit/{{ notebook.id }}" method="post">
            {% csrf_token %}
            <div class="label">Notebook name:</div>
            <div class="notebook-edit-name">
                {{ form.name }}
            </div>
            <div class="label">Notebook decription:</div>
            <div class="notebook-edit-desc">
                {{ form.desc }}
            </div>
            <div class="note-bottom">
                <input type="submit" value = "Save">
                <a href="{% url 'noter:notebook_delete' notebook.id %}" class="button delete">Delete</a>
                <div class="warning">Warning! If you delete your notebook, you will also delete every note inside it.</div>
            </div>
        </form>
    </div>

{% endblock %}

noter/noter/templates/noter/index.html
{% extends "noter\base.html" %}

{% block content %}
<div class="main-content">

    {% if notebooks_list %}
        {% for notebook in notebooks_list %}
            <a href="{% url 'noter:notebook' notebook.id %}" class="notebook-item">
                <div class="notebook-title">{{ notebook.name }}</div>
                <span class="dotted-divider"></span>
                <div class="notebook-desc">{{ notebook.desc }}</div>
            </a>
        {% endfor %}
        
    {% else %}
        <p>There are no notebooks yet. Create one by pressing "+" buttom on the bottom right of your screen.</p>
    {% endif %}
</div>
<a href="{% url 'noter:notebook_create' %}" class="create">+</a>
{% endblock %}

noter/noter/templates/noter/login.html
{% extends "noter\base.html" %}

{% block content %}
    <div class="notes-content">
        <form action="/noter/login/" method="post">
            {% csrf_token %}
            <div class="label">Username:</div>    
            <div class="general-form-input">
                {{ form.username }}
            </div>
            <div class="label">Password:</div>
            <div class="general-form-input">
                {{ form.password }}
            </div>
            {{ error }}
            <div class="note-bottom">
                <input type="submit" value="Log in">
                <a href="{% url 'noter:register' %}" class="button">Register</a>
            </div>
        </form>
    </div>
{% endblock %}

noter/noter/templates/noter/note.html
{% extends "noter\base.html" %}

{% block content %}
    <div class="notes-content">
        <a href="{% url 'noter:notebook' notebook.id %}" class="note-item">Go back to <b>{{ notebook.name }}</b></a>
    </div>
    <div class="notes-content">
        <form action="/noter/note/{{note.id}}/" method="post">        
            {% csrf_token %}
            <div class="note-title">
                {{ form.title }}
            </div>
            <div class="note-text">
                {{ form.text }}
            </div>
            {{ error }}
            <div class="note-bottom">
                <input type="submit" value="Save">
                <a href="{% url 'noter:note_delete' note.id %}" class="button delete">Delete</a>
            </div>
        </form>
    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $('.note-title input').focus()
        })

        $('textarea').on('input', function() {
            this.style.height = "";
            this.style.height = this.scrollHeight + "px";
        });

        $('.note-title input').keydown(function (e) {
            if (e.keyCode == 13) {
                $('.note-text textarea').focus();
                e.preventDefault();
                return false;
            }
        })
        
    </script>


{% endblock %}

noter/noter/templates/noter/notebook.html
{% extends "noter\base.html" %}

{% block content %}
    <div class="notes-content">
        <a href="{% url 'noter:index' %}" class="note-item">Back to notebooks</b></a>
    </div>
    <div class="notes-content">
        <div class="notebook-title-desc">{{ notebook.name }}</div>
        <a href="{% url 'noter:notebook_edit' notebook.id %}" class="notebook-edit button">Edit</a>
        <div style="clear: both;"></div>
        <div class="notebook-inside-desc">{{ notebook.desc }}</div>
    </div>
    <div class="notes-content">
        {% if notes %}
            {% for note in notes %}
                <a href="{% url 'noter:note' note.id %}" class="note-item">
                    {% if note.title != "" or note.text != "" %}
                        <h3>{{ note.title }}</h3>
                        <p>{{ note.text }}</p>
                    {% else %}
                        <p>Empty note</p>
                    {% endif %}
                </a>
            {% endfor %}
        {% else %}
            <p>There are no notes here yet. Create one by pressing "+" button on the bottom-right of your screen.</p>
        {% endif %}
        
    </div>
    <a href="{% url 'noter:note_create' notebook.id %}" class="create">+</a>
{% endblock %}

noter/noter/templates/noter/notebook_creation.html
{% extends "noter\base.html" %}

{% block content %}
    <div class="notes-content">
        <h2>Notebook creation</h2>
        <form action="/noter/create_notebook/" method="post">
            {% csrf_token %}
            <div class="label">Notebook name:</div>
            <div class="notebook-edit-name">
                {{ form.name }}
            </div>
            <div class="label">Notebook decription:</div>
            <div class="notebook-edit-desc">
                {{ form.desc }}
            </div>
            <div class="note-bottom">
                <input type="submit" value = "Create">
            </div>
        </form>
    </div>
{% endblock %}

noter/noter/templates/noter/register.html
{% extends "noter\base.html" %}

{% block content %}
    <div class="notes-content">
        <h2>Registration</h2>
        <form action="/noter/register/" method="post">
            {% csrf_token %}
            <div class="label">First name</div>
            <div class="general-form-input">
                {{ form.firstname }}
            </div>
            <div class="label">Last name</div>
            <div class="general-form-input">
                {{ form.lastname }}
            </div>
            <div class="label">Username</div>
            <div class="general-form-input">
                {{ form.username }}
            </div>
            <div class="label">Email</div>
            <div class="general-form-input">
                {{ form.email }}
            </div>
            <div class="label">Password</div>
            <div class="general-form-input">
                {{ form.password1 }}
            </div>
            <div class="label">Repeat password</div>
            <div class="general-form-input">
                {{ form.password2 }}
            </div>
            {{ error }}
            <div class="note-bottom">
                <input type="submit" value="Register">
                <a href="{% url 'noter:login' %}" class="button">Login</a>
            </div>
        </form>
    </div>

{% endblock %}

noter/noter/templates/noter/signup.html
<h2>Sign up</h2>
<form action="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>

noter/noter/templates/noter/user_settings.html
{% extends 'noter\base.html' %}

{% block content %}

    <div class="notes-content">
        <a href="{% url 'noter:index' %}" class="note-item">Back to notebooks</a>
    </div>
    <div class="notes-content">
        <h2>Edit your user information:</h2>
        <form action="/noter/user_settings/" method = "post">
            {% csrf_token %}
            <div class="label">Username:</div>
            <div class="notebook-edit-name">
                {{ form.username }}
            </div>
            <div class="label">Email:</div>
            <div class="notebook-edit-name">
                {{ form.email }}
            </div>
            <div class="label">First name:</div>
            <div class="notebook-edit-name">
                {{ form.firstname }}
            </div>
            <div class="label">Last name:</div>
            <div class="notebook-edit-name">
                {{ form.lastname }}
            </div>
            {{ error }}
            <div class="note-bottom">
                <input type="submit" value = "Save">
            </div>
        </form>
    </div>

{% endblock %}